// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: protos/metrics.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsService_SubscribeMetrics_FullMethodName     = "/metrics.MetricsService/SubscribeMetrics"
	MetricsService_GetHistoricalMetrics_FullMethodName = "/metrics.MetricsService/GetHistoricalMetrics"
	MetricsService_GetDevices_FullMethodName           = "/metrics.MetricsService/GetDevices"
	MetricsService_UpdateConfig_FullMethodName         = "/metrics.MetricsService/UpdateConfig"
)

// MetricsServiceClient is the client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The metrics service definition.
type MetricsServiceClient interface {
	// Stream of real-time metric updates
	SubscribeMetrics(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricUpdate], error)
	// Fetch historical metrics
	GetHistoricalMetrics(ctx context.Context, in *HistoricalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricPoint], error)
	// Get available devices
	GetDevices(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*DeviceList, error)
	// Update configuration
	UpdateConfig(ctx context.Context, in *ConfigUpdate, opts ...grpc.CallOption) (*ConfigResponse, error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) SubscribeMetrics(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[0], MetricsService_SubscribeMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscriptionRequest, MetricUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_SubscribeMetricsClient = grpc.ServerStreamingClient[MetricUpdate]

func (c *metricsServiceClient) GetHistoricalMetrics(ctx context.Context, in *HistoricalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricPoint], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[1], MetricsService_GetHistoricalMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HistoricalRequest, MetricPoint]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_GetHistoricalMetricsClient = grpc.ServerStreamingClient[MetricPoint]

func (c *metricsServiceClient) GetDevices(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*DeviceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceList)
	err := c.cc.Invoke(ctx, MetricsService_GetDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) UpdateConfig(ctx context.Context, in *ConfigUpdate, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, MetricsService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServiceServer is the server API for MetricsService service.
// All implementations must embed UnimplementedMetricsServiceServer
// for forward compatibility.
//
// The metrics service definition.
type MetricsServiceServer interface {
	// Stream of real-time metric updates
	SubscribeMetrics(*SubscriptionRequest, grpc.ServerStreamingServer[MetricUpdate]) error
	// Fetch historical metrics
	GetHistoricalMetrics(*HistoricalRequest, grpc.ServerStreamingServer[MetricPoint]) error
	// Get available devices
	GetDevices(context.Context, *DeviceRequest) (*DeviceList, error)
	// Update configuration
	UpdateConfig(context.Context, *ConfigUpdate) (*ConfigResponse, error)
	mustEmbedUnimplementedMetricsServiceServer()
}

// UnimplementedMetricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServiceServer struct{}

func (UnimplementedMetricsServiceServer) SubscribeMetrics(*SubscriptionRequest, grpc.ServerStreamingServer[MetricUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) GetHistoricalMetrics(*HistoricalRequest, grpc.ServerStreamingServer[MetricPoint]) error {
	return status.Error(codes.Unimplemented, "method GetHistoricalMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) GetDevices(context.Context, *DeviceRequest) (*DeviceList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedMetricsServiceServer) UpdateConfig(context.Context, *ConfigUpdate) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedMetricsServiceServer) mustEmbedUnimplementedMetricsServiceServer() {}
func (UnimplementedMetricsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServiceServer will
// result in compilation errors.
type UnsafeMetricsServiceServer interface {
	mustEmbedUnimplementedMetricsServiceServer()
}

func RegisterMetricsServiceServer(s grpc.ServiceRegistrar, srv MetricsServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsService_ServiceDesc, srv)
}

func _MetricsService_SubscribeMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetricsServiceServer).SubscribeMetrics(m, &grpc.GenericServerStream[SubscriptionRequest, MetricUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_SubscribeMetricsServer = grpc.ServerStreamingServer[MetricUpdate]

func _MetricsService_GetHistoricalMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HistoricalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetricsServiceServer).GetHistoricalMetrics(m, &grpc.GenericServerStream[HistoricalRequest, MetricPoint]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_GetHistoricalMetricsServer = grpc.ServerStreamingServer[MetricPoint]

func _MetricsService_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetDevices(ctx, req.(*DeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).UpdateConfig(ctx, req.(*ConfigUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsService_ServiceDesc is the grpc.ServiceDesc for MetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevices",
			Handler:    _MetricsService_GetDevices_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _MetricsService_UpdateConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeMetrics",
			Handler:       _MetricsService_SubscribeMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetHistoricalMetrics",
			Handler:       _MetricsService_GetHistoricalMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/metrics.proto",
}
